services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitadmin
      RABBITMQ_DEFAULT_PASS: 123456
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rabbit_todo
      MYSQL_USER: rabbitadmin
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306" # HostPort:ContainerPort
    volumes:
      - mysql_data:/var/lib/mysql
  
  rabbit.api:
    container_name: rabbit.api
    build:
      context: .
      dockerfile: Rabbit.API/Dockerfile
    ports:
      - "5000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    command: /bin/sh -c "sleep 10 && dotnet Rabbit.Audit.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:8000
  
  rabbit.audit:
    container_name: rabbit.audit
    build:
      context: .
      dockerfile: Rabbit.Audit/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Development

volumes:
  mysql_data:
